replicaCount: 1

image:
  repository: quesma/quesma
  pullPolicy: Always
  tag: "" # It's set in `deployment.yaml` template if empty via .Chart.AppVersion

# --- Service, ingress, resources, probes, autoscaling, etc. stay unchanged ---

# IMPORTANT: The main ConfigMap volume is now defined in the template (not here).
# Use these ONLY for adding extra volumes/mounts in addition to the config volume.
extraVolumes: []
  # - name: some-extra-volume
  #   emptyDir: {}

extraVolumeMounts: []
  # - name: some-extra-volume
  #   mountPath: /some/path

# These are environment variables passed to Quesma container
env:
  - name: QUESMA_CONFIG_FILE
    value: "/quesma-configuration/quesma-config.yaml"

# Default configuration options rendered into the Quesma config file
config:
  quesmaConfigurationYaml:
    licenseKey: #PLACE_YOUR_QUESMA_LICENSE_KEY_HERE
    logging:
      level: "debug"
      fileLogging: true
    frontendConnectors:
      - name: elastic-ingest
        type: elasticsearch-fe-ingest
        config:
          listenPort: 8080
          disableAuth: true
      - name: elastic-query
        type: elasticsearch-fe-query
        config:
          listenPort: 8080
          disableAuth: true
    backendConnectors:
      - name: my-minimal-elasticsearch
        type: elasticsearch
        config:
          url: "https://opensearch-cluster-master:9200"
          user: admin
          password: 'myStrongPassword@123!'
      - name: my-sqldb-data-source
        type: #PLACE_YOUR_CONNECTOR_TYPE_HERE - `clickhouse`, `hydrolix` or `clickhouse-os`
        config:
          url: #PLACE_YOUR_SQL_URL_HERE
          user: #PLACE_YOUR_SQL_USER_HERE
          password: #PLACE_YOUR_SQL_PASS_HERE
          database: #PLACE_YOUR_SQL_DB_NAME_HERE
    processors:
      - name: my-query-processor
        type: quesma-v1-processor-query
        config:
          indexes:
            my_example_table:
              target: [ my-sqldb-data-source ]
            '*':
              target: [ my-sqldb-data-source ]
      - name: my-ingest-processor
        type: quesma-v1-processor-ingest
        config:
          indexes:
            my_example_table:
              target: [ my-sqldb-data-source ]
            '*':
              target: [ my-sqldb-data-source ]
    pipelines:
      - name: my-sqldb-query-pipeline
        frontendConnectors: [ elastic-query ]
        processors: [ my-query-processor ]
        backendConnectors: [ my-minimal-elasticsearch, my-sqldb-data-source ]
      - name: my-sqldb-ingest-pipeline
        frontendConnectors: [ elastic-ingest ]
        processors: [ my-ingest-processor ]
        backendConnectors: [ my-minimal-elasticsearch, my-sqldb-data-source ]

opensearch:
  enabled: false
  persistence:
    enabled: false
  extraEnvs:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: myStrongPassword@123!

opensearch-dashboards:
  enabled: false
