apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quesma.fullname" . }}
  labels:
    {{- include "quesma.labels" . | nindent 4 }}
spec:
  {{- $stype := default "Recreate" .Values.deploymentStrategy.type }}
  strategy:
    type: {{ $stype }}
    {{- if and (eq $stype "RollingUpdate") (.Values.deploymentStrategy.rollingUpdate) }}
    rollingUpdate:
      {{- toYaml .Values.deploymentStrategy.rollingUpdate | nindent 6 }}
    {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "quesma.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- /* These MUST include the selector labels */}}
        {{- include "quesma.selectorLabels" . | nindent 8 }}
        {{- /* Optionally include broader chart labels */}}
        {{- include "quesma.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            # Mount the generated ConfigMap with the rendered Quesma config
            - name: quesma-config-volume
              mountPath: /quesma-configuration/quesma-config.yaml
              subPath: quesma-config.yaml
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: quesma-config-volume
          configMap:
            name: {{ include "quesma.fullname" . }}-config
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
