apiVersion: v1
kind: Service
metadata:
  name: {{ include "quesma.fullname" . }}-frontend
{{/*  labels:*/}}
{{/*    {{- include "quesma.labels" . | nindent 4 }}*/}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "quesma.selectorLabels" . | nindent 4 }}
