apiVersion: v1
kind: Service
metadata:
  name: {{ include "quesma.fullname" . }}
  labels:
    {{- include "quesma.labels" . | nindent 4 }}
  {{- $svc := default (dict) .Values.service -}}
  {{- with (index $svc "annotations") }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ default "ClusterIP" (index $svc "type") }}
  ports:
    - port: {{ default 8080 (index $svc "port") }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "quesma.selectorLabels" . | nindent 4 }}
