apiVersion: v1
kind: Service
metadata:
  name: {{ include "quesma.fullname" . }}-admin
{{/*  labels:*/}}
{{/*    {{- include "quesma.labels" . | nindent 4 }}*/}}
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: 9999
  selector:
    {{- include "quesma.selectorLabels" . | nindent 4 }}
